"""update completed_features fields

Revision ID: a1153122d3a0
Revises: cd684ceb33c0
Create Date: 2026-07-16 12:25:02.044317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1153122d3a0'
down_revision: Union[str, Sequence[str], None] = 'cd684ceb33c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('completed_features', sa.Column('name', sa.String(), nullable=False))
    op.add_column('completed_features', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('completed_features', sa.Column('domain', sa.String(), nullable=True))
    op.add_column('completed_features', sa.Column('tech_details', sa.Text(), nullable=True))
    op.drop_column('completed_features', 'feature')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('completed_features', sa.Column('feature', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('completed_features', 'tech_details')
    op.drop_column('completed_features', 'domain')
    op.drop_column('completed_features', 'description')
    op.drop_column('completed_features', 'name')
    # ### end Alembic commands ###
